---
# tasks file for ansible-kubeseal
- name: Get latest Release from kubeseal
  shell: curl -Lo /tmp/kubeseal.tar.gz https://github.com/bitnami-labs/sealed-secrets/releases/download/$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest | grep tag_name | cut -d '"' -f 4)/kubeseal-$(curl -s https://api.github.com/repos/bitnami-labs/sealed-secrets/releases/latest | grep tag_name | cut -d '"' -f 4 | tr -d v)-linux-amd64.tar.gz
  args:
    warn: no
  when: ansible_architecture == 'x86_64'
  tags: kubeseal

- name: Unarchive a file
  shell: tar -xvf /tmp/kubeseal.tar.gz -C /usr/local/bin/ kubeseal
  # args:
  #   warn: no
  tags: kubeseal

- name: Verify kubeseal exists
  stat: path=/usr/local/bin/kubeseal
  register: kubeseal_stat
  tags: kubeseal

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/kubeseal
    owner: root
    group: root
    mode: '0755'
  tags: kubeseal

- command: kubeseal --version
  register: result_kubeseal
  failed_when: false
  changed_when: false
  tags: kubeseal

- debug:
    var: result_kubeseal.stdout
  tags: kubeseal
